plugins {
    id 'java'
    id 'io.quarkus'
}

repositories {
    mavenCentral()
    maven {
        url 'https://maven.dcm4che.org/'
    }
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")

    implementation 'io.quarkus:quarkus-rest-jackson'
    implementation 'io.quarkus:quarkus-smallrye-openapi'
    implementation 'io.quarkus:quarkus-arc'

    implementation 'org.dcm4che:dcm4che-core:5.29.1'
    implementation 'commons-io:commons-io:2.21.0'

    implementation 'io.quarkus:quarkus-hibernate-validator'

    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
    testImplementation 'org.assertj:assertj-core:3.27.7'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

compileJava.options.encoding = 'UTF-8'
compileJava.options.compilerArgs << '-parameters'
